[project]
name = "2025-tvdi-pythonweb"
version = "0.1.0"
description = "For class_職能發展學院_flaskWeb"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.2",
    "matplotlib>=3.10.7",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
]
